### ISSUE TITLE
Ambient music not found

### ISSUE THREAD

**Issue by mtbrenner** [NFINIT-Development/Astroblock2#10]
This message repeats in the logfile. Probable reason is that the file ambience_music/music/debris.mp3 doesn't exist, instead there is only debris.wav. Converting it to debris.mp3 should fix this. This should be done for all references in ambience.properties.

[07:51:02] [Ambience Player Thread/ERROR]: File C:\Users\Martin\Twitch\Minecraft\Instances\AstroBlock 2 (7)\ambience_music\music\debris.mp3 not found. Fix your Ambience config!
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: java.io.FileNotFoundException: C:\Users\Martin\Twitch\Minecraft\Instances\AstroBlock 2 (7)\ambience_music\music\debris.mp3 (The system cannot find the file specified)
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: 	at java.io.FileInputStream.open0(Native Method)
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: 	at vazkii.ambience.SongLoader.getStream(SongLoader.java:162)
[07:51:02] [Ambience Player Thread/INFO]: [vazkii.ambience.SongLoader:getStream:165]: 	at vazkii.ambience.PlayerThread.run(PlayerThread.java:53)

**Comment by knoxhack** [comment]
Fixed in version 0.4.6
